# .github/workflows/java-app.yml
name: Java application

on:
 push:
  branches:
   -main

jobs:
  test:
   runs-on: ubuntu-latest
   
   steps:
     # リポジトリのチェックアウト
     - name: Check out repository
       uses: actions/checkout@v3
       
     # Javaのセットアップ
